2024-03-29 14:45:17,125 INFO    MainThread:97043 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-03-29 14:45:17,125 INFO    MainThread:97043 [wandb_setup.py:_flush():76] Configure stats pid to 97043
2024-03-29 14:45:17,125 INFO    MainThread:97043 [wandb_setup.py:_flush():76] Loading settings from /home/kajetan/.config/wandb/settings
2024-03-29 14:45:17,125 INFO    MainThread:97043 [wandb_setup.py:_flush():76] Loading settings from /home/kajetan/Documents/pytorch_deep_learning/wandb/settings
2024-03-29 14:45:17,125 INFO    MainThread:97043 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-29 14:45:17,126 INFO    MainThread:97043 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-29 14:45:17,126 INFO    MainThread:97043 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-29 14:45:17,126 INFO    MainThread:97043 [wandb_init.py:_log_setup():526] Logging user logs to /home/kajetan/Documents/pytorch_deep_learning/wandb/run-20240329_144517-i5zw91bo/logs/debug.log
2024-03-29 14:45:17,126 INFO    MainThread:97043 [wandb_init.py:_log_setup():527] Logging internal logs to /home/kajetan/Documents/pytorch_deep_learning/wandb/run-20240329_144517-i5zw91bo/logs/debug-internal.log
2024-03-29 14:45:17,126 INFO    MainThread:97043 [wandb_init.py:_jupyter_setup():472] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x738c40a6be10>
2024-03-29 14:45:17,126 INFO    MainThread:97043 [wandb_init.py:init():566] calling init triggers
2024-03-29 14:45:17,126 INFO    MainThread:97043 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-29 14:45:17,126 INFO    MainThread:97043 [wandb_init.py:init():616] starting backend
2024-03-29 14:45:17,126 INFO    MainThread:97043 [wandb_init.py:init():620] setting up manager
2024-03-29 14:45:17,129 INFO    MainThread:97043 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-29 14:45:17,131 INFO    MainThread:97043 [wandb_init.py:init():628] backend started and connected
2024-03-29 14:45:17,145 INFO    MainThread:97043 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-03-29 14:45:17,145 INFO    MainThread:97043 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-29 14:45:17,145 INFO    MainThread:97043 [wandb_init.py:init():720] updated telemetry
2024-03-29 14:45:17,154 INFO    MainThread:97043 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-29 14:45:17,573 ERROR   MainThread:97043 [wandb_init.py:init():779] encountered error: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-29 14:45:17,744 ERROR   MainThread:97043 [wandb_init.py:init():1194] It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
Traceback (most recent call last):
  File "/home/kajetan/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 1176, in init
    run = wi.init()
          ^^^^^^^^^
  File "/home/kajetan/anaconda3/lib/python3.11/site-packages/wandb/sdk/wandb_init.py", line 785, in init
    raise error
wandb.errors.CommError: It appears that you do not have permission to access the requested resource. Please reach out to the project owner to grant you access. If you have the correct permissions, verify that there are no issues with your networking setup.(Error 404: Not Found)
2024-03-29 15:27:35,170 INFO    MainThread:97043 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-03-29 15:27:35,170 INFO    MainThread:97043 [wandb_setup.py:_flush():76] Configure stats pid to 97043
2024-03-29 15:27:35,170 INFO    MainThread:97043 [wandb_setup.py:_flush():76] Loading settings from /home/kajetan/.config/wandb/settings
2024-03-29 15:27:35,170 INFO    MainThread:97043 [wandb_setup.py:_flush():76] Loading settings from /home/kajetan/Documents/pytorch_deep_learning/wandb/settings
2024-03-29 15:27:35,170 INFO    MainThread:97043 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-29 15:27:35,170 INFO    MainThread:97043 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-29 15:27:35,170 INFO    MainThread:97043 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-29 15:27:35,170 INFO    MainThread:97043 [wandb_init.py:_log_setup():526] Logging user logs to /home/kajetan/Documents/pytorch_deep_learning/wandb/run-20240329_152735-935tj5bb/logs/debug.log
2024-03-29 15:27:35,170 INFO    MainThread:97043 [wandb_init.py:_log_setup():527] Logging internal logs to /home/kajetan/Documents/pytorch_deep_learning/wandb/run-20240329_152735-935tj5bb/logs/debug-internal.log
2024-03-29 15:27:35,171 INFO    MainThread:97043 [wandb_init.py:init():566] calling init triggers
2024-03-29 15:27:35,171 INFO    MainThread:97043 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-29 15:27:35,171 INFO    MainThread:97043 [wandb_init.py:init():616] starting backend
2024-03-29 15:27:35,171 INFO    MainThread:97043 [wandb_init.py:init():620] setting up manager
2024-03-29 15:27:35,176 INFO    MainThread:97043 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-29 15:27:35,177 INFO    MainThread:97043 [wandb_init.py:init():628] backend started and connected
2024-03-29 15:27:35,193 INFO    MainThread:97043 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-03-29 15:27:35,193 INFO    MainThread:97043 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-29 15:27:35,194 INFO    MainThread:97043 [wandb_init.py:init():720] updated telemetry
2024-03-29 15:27:35,213 INFO    MainThread:97043 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-29 15:27:35,750 INFO    MainThread:97043 [wandb_run.py:_on_init():2254] communicating current version
2024-03-29 15:28:05,754 INFO    MainThread:97043 [wandb_init.py:init():804] starting run threads in backend
2024-03-29 15:28:35,776 INFO    MainThread:97043 [wandb_run.py:_console_start():2233] atexit reg
2024-03-29 15:28:35,776 INFO    MainThread:97043 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-03-29 15:28:35,776 INFO    MainThread:97043 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-03-29 15:28:35,777 INFO    MainThread:97043 [wandb_run.py:_redirect():2178] Redirects installed.
2024-03-29 15:28:35,777 INFO    MainThread:97043 [wandb_init.py:init():847] run started, returning control to user process
