2024-03-29 16:15:18,622 INFO    MainThread:124600 [wandb_setup.py:_flush():76] Current SDK version is 0.16.2
2024-03-29 16:15:18,622 INFO    MainThread:124600 [wandb_setup.py:_flush():76] Configure stats pid to 124600
2024-03-29 16:15:18,622 INFO    MainThread:124600 [wandb_setup.py:_flush():76] Loading settings from /home/kajetan/.config/wandb/settings
2024-03-29 16:15:18,622 INFO    MainThread:124600 [wandb_setup.py:_flush():76] Loading settings from /home/kajetan/Documents/pytorch_deep_learning/wandb/settings
2024-03-29 16:15:18,622 INFO    MainThread:124600 [wandb_setup.py:_flush():76] Loading settings from environment variables: {}
2024-03-29 16:15:18,623 INFO    MainThread:124600 [wandb_setup.py:_flush():76] Applying setup settings: {'_disable_service': False}
2024-03-29 16:15:18,623 INFO    MainThread:124600 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-03-29 16:15:18,623 INFO    MainThread:124600 [wandb_init.py:_log_setup():526] Logging user logs to /home/kajetan/Documents/pytorch_deep_learning/wandb/run-20240329_161518-z1bt8b0g/logs/debug.log
2024-03-29 16:15:18,623 INFO    MainThread:124600 [wandb_init.py:_log_setup():527] Logging internal logs to /home/kajetan/Documents/pytorch_deep_learning/wandb/run-20240329_161518-z1bt8b0g/logs/debug-internal.log
2024-03-29 16:15:18,623 INFO    MainThread:124600 [wandb_init.py:init():566] calling init triggers
2024-03-29 16:15:18,623 INFO    MainThread:124600 [wandb_init.py:init():573] wandb.init called with sweep_config: {}
config: {}
2024-03-29 16:15:18,623 INFO    MainThread:124600 [wandb_init.py:init():591] re-initializing run, found existing run on stack: sax6jrv2
2024-03-29 16:15:18,625 INFO    MainThread:124600 [wandb_run.py:_finish():1962] finishing run frackowiak/pytorch_computer_vision/sax6jrv2
2024-03-29 16:15:18,625 INFO    MainThread:124600 [jupyter.py:save_history():445] not saving jupyter history
2024-03-29 16:15:18,625 INFO    MainThread:124600 [jupyter.py:save_ipynb():373] not saving jupyter notebook
2024-03-29 16:15:18,625 INFO    MainThread:124600 [wandb_init.py:_jupyter_teardown():454] cleaning up jupyter logic
2024-03-29 16:15:18,625 INFO    MainThread:124600 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-03-29 16:15:18,626 INFO    MainThread:124600 [wandb_run.py:_restore():2185] restore
2024-03-29 16:15:18,626 INFO    MainThread:124600 [wandb_run.py:_restore():2191] restore done
2024-03-29 16:15:22,160 INFO    MainThread:124600 [wandb_run.py:_footer_history_summary_info():3857] rendering history
2024-03-29 16:15:22,160 INFO    MainThread:124600 [wandb_run.py:_footer_history_summary_info():3889] rendering summary
2024-03-29 16:15:22,162 INFO    MainThread:124600 [wandb_run.py:_footer_sync_info():3816] logging synced files
2024-03-29 16:15:22,443 INFO    MainThread:124600 [wandb_init.py:init():616] starting backend
2024-03-29 16:15:22,443 INFO    MainThread:124600 [wandb_init.py:init():620] setting up manager
2024-03-29 16:15:22,446 INFO    MainThread:124600 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2024-03-29 16:15:22,446 INFO    MainThread:124600 [wandb_init.py:init():628] backend started and connected
2024-03-29 16:15:22,459 INFO    MainThread:124600 [wandb_run.py:_label_probe_notebook():1294] probe notebook
2024-03-29 16:15:22,459 INFO    MainThread:124600 [wandb_run.py:_label_probe_notebook():1304] Unable to probe notebook: 'NoneType' object has no attribute 'get'
2024-03-29 16:15:22,459 INFO    MainThread:124600 [wandb_init.py:init():720] updated telemetry
2024-03-29 16:15:22,465 INFO    MainThread:124600 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-03-29 16:15:23,665 INFO    MainThread:124600 [wandb_run.py:_on_init():2254] communicating current version
2024-03-29 16:15:23,856 INFO    MainThread:124600 [wandb_run.py:_on_init():2263] got version response upgrade_message: "wandb version 0.16.5 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-03-29 16:15:23,857 INFO    MainThread:124600 [wandb_init.py:init():804] starting run threads in backend
2024-03-29 16:15:37,956 INFO    MainThread:124600 [wandb_run.py:_console_start():2233] atexit reg
2024-03-29 16:15:37,956 INFO    MainThread:124600 [wandb_run.py:_redirect():2088] redirect: wrap_raw
2024-03-29 16:15:37,956 INFO    MainThread:124600 [wandb_run.py:_redirect():2153] Wrapping output streams.
2024-03-29 16:15:37,956 INFO    MainThread:124600 [wandb_run.py:_redirect():2178] Redirects installed.
2024-03-29 16:15:37,957 INFO    MainThread:124600 [wandb_init.py:init():847] run started, returning control to user process
2024-03-29 16:16:04,639 INFO    MainThread:124600 [wandb_run.py:_finish():1962] finishing run frackowiak/pytorch_computer_vision1/z1bt8b0g
2024-03-29 16:16:04,639 INFO    MainThread:124600 [wandb_run.py:_atexit_cleanup():2202] got exitcode: 0
2024-03-29 16:16:04,639 INFO    MainThread:124600 [wandb_run.py:_restore():2185] restore
2024-03-29 16:16:04,639 INFO    MainThread:124600 [wandb_run.py:_restore():2191] restore done
2024-03-29 16:16:08,837 INFO    MainThread:124600 [wandb_run.py:_footer_history_summary_info():3857] rendering history
2024-03-29 16:16:08,838 INFO    MainThread:124600 [wandb_run.py:_footer_history_summary_info():3889] rendering summary
2024-03-29 16:16:08,841 INFO    MainThread:124600 [wandb_run.py:_footer_sync_info():3816] logging synced files
